# Theme
remote_theme: 'peppelongo96/find-me-page@theme'

# Advanced settings
plugins: 
  - jekyll-remote-theme

# Title and tag line
title: ''
tab_title: ''

# Tracking - Visit https://freehitcounters.org/ and get your ID
id_visitors_badge:

# Copyright author
author: peppelongo96

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: ''
twitter: ''
linkedin: ''
instagram: ''
github: ''
email: ''
phone: ''
whatsapp: ''
telegram: ''

social-links-order: [phone, email, linkedin, github, whatsapp, telegram, facebook, instagram, twitter]

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook

  - name: twitter
    url-pattern: twitter.com/__USERNAME__
    icon-class: fab fa-2x fa-twitter

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__
    icon-class: fab fa-2x fa-linkedin

  - name: instagram
    url-pattern: instagram.com/__USERNAME__
    icon-class: fab fa-2x fa-instagram

  - name: github
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: telegram
    url-pattern: telegram.me/__USERNAME__
    icon-class: fab fa-2x fa-telegram

  - name: email
    url-scheme: 'mailto:'
    url-pattern: __USERNAME__
    icon-class: fas fa-2x fa-at
    
  - name: phone
    url-scheme: 'tel:'
    url-pattern: __USERNAME__
    icon-class: fas fa-2x fa-phone-alt
   
  - name: whatsapp
    url-pattern: wa.me/__USERNAME__
    icon-class: fab fa-2x fa-whatsapp
