# Theme - DON'T EDIT
remote_theme: 'peppelongo96/find-me-page@theme'
plugins: 
  - jekyll-remote-theme

# Titles
title: ''
tab_title: ''

# Visitors badge 
# INSTRUCTIONS or jump and leave blank if you don't want it
# - Go to https://freehitcounters.org/
# - Select your favourite badge and generate the HTML code
# - Compare with this template and fill the following as indicate:
#
#  <script type="text/javascript" src="https://freehitcounters.org/count/__COUNTER_CODE_VISITORS_BADGE__"></script><br>
#  <a href='__ADS_HREF_VISITORS_BADGE__'>__ADS_HREF_LABEL_VISITORS_BADGE__</a> 
#  <script type='text/javascript' src='https://whomania.com/ctr?id=__ID_VISITORS_BADGE__'></script>
#
counter_code_visitors_badge:
id_visitors_badge:
ads_href_visitors_badge:
ads_href_label_visitors_badge: 

# Copyright author
author: peppelongo96

# Images
avatar: ''
background: ''
favicon: ''

# Social links
facebook: ''
twitter: ''
linkedin: ''
instagram: ''
github: ''
email: ''
phone: ''
whatsapp: ''
telegram: ''

social-links-order: [phone, email, linkedin, github, whatsapp, telegram, facebook, instagram, twitter]

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**

social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook

  - name: twitter
    url-pattern: twitter.com/__USERNAME__
    icon-class: fab fa-2x fa-twitter

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__
    icon-class: fab fa-2x fa-linkedin

  - name: instagram
    url-pattern: instagram.com/__USERNAME__
    icon-class: fab fa-2x fa-instagram

  - name: github
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: telegram
    url-pattern: telegram.me/__USERNAME__
    icon-class: fab fa-2x fa-telegram

  - name: email
    url-scheme: 'mailto:'
    url-pattern: __USERNAME__
    icon-class: fas fa-2x fa-at
    
  - name: phone
    url-scheme: 'tel:'
    url-pattern: __USERNAME__
    icon-class: fas fa-2x fa-phone-alt
   
  - name: whatsapp
    url-pattern: wa.me/__USERNAME__
    icon-class: fab fa-2x fa-whatsapp
